### ISSUE TITLE
Why is there no method for set tag? 

### ISSUE THREAD

**Issue by yurishkuro** [opentracing-contrib/java-span-reporter#2]
For example, if we were to use this reporter interface to emit RPC metrics, as done with [SpanObserver here](https://github.com/uber/jaeger-client-go/blob/master/rpcmetrics/observer.go), then tags would be critical.

PS: I think "observer" would've been more appropriate name than "reporter" here.

cc @davidB

**Comment by davidB** [comment]
I don't see the use case to report when a tag is set to the span. Today my use case for metrics (and for log) is only to report start, stop, log, duration (timing stop-start), and count. I don't see the need to report other change on the span. 
It's why I choose reporter vs observer. Observer imply rules that match none of initial list of use cases: 
* to allow dynamic register/unregister of observers
* to notify change about every span's part (like tag)

Can you share a use case that require to be notify about set tag ?

PS: Sorry for late reply (I was busy)

**Comment by yurishkuro** [comment]
If your use case is metrics, why do you need to intercept logs?

The reason you need tags for metrics is because failed spans are marked with `error: true` tag.

**Comment by davidB** [comment]
The reporter for metrics will ignore log (and maybe start), but the
reporter for log used the start, finish, log.

When reporter is called for start / finish / log, it have read access to
tags (workaround of the OT api). So it can also report some or all tags
including "error: true". reporting metrics with tab label, error: true or
http status is idem (IMHO)
